package handler

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/nibankougen/LowPolyWorld/api/internal/middleware"
	"github.com/nibankougen/LowPolyWorld/api/internal/response"
)

type violationReportRow struct {
	ID          string    `json:"id"`
	ReporterID  string    `json:"reporter_id"`
	TargetID    string    `json:"target_id"`
	Reason      string    `json:"reason"`
	Detail      string    `json:"detail"`
	AutoGenerated bool    `json:"is_auto_generated"`
	CreatedAt   time.Time `json:"created_at"`
}

// AdminListViolationReports handles GET /admin/violation-reports.
// Query params: target_id, after (cursor by id).
func (h *Handler) AdminListViolationReports(w http.ResponseWriter, r *http.Request) {
	targetFilter := r.URL.Query().Get("target_id")
	after := r.URL.Query().Get("after")
	limit := 50

	rows, err := h.DB.Query(r.Context(),
		`SELECT id, reporter_id, target_id, reason, detail, is_auto_generated, created_at
		 FROM user_violation_reports
		 WHERE ($1 = '' OR target_id = $1::UUID)
		   AND ($2 = '' OR created_at < (SELECT created_at FROM user_violation_reports WHERE id = $2::UUID))
		 ORDER BY created_at DESC
		 LIMIT $3`,
		targetFilter, after, limit+1,
	)
	if err != nil {
		h.Logger.Error("admin list violation reports", "error", err)
		response.InternalError(w, r, h.Cfg.IsProduction())
		return
	}
	defer rows.Close()

	var reports []violationReportRow
	for rows.Next() {
		var rr violationReportRow
		if err := rows.Scan(&rr.ID, &rr.ReporterID, &rr.TargetID,
			&rr.Reason, &rr.Detail, &rr.AutoGenerated, &rr.CreatedAt); err != nil {
			continue
		}
		reports = append(reports, rr)
	}

	var cursor response.Cursor
	if len(reports) > limit {
		reports = reports[:limit]
		cursor.Next = reports[len(reports)-1].ID
	}
	response.JSONCursor(w, http.StatusOK, reports, cursor)
}

type auditLogRow struct {
	ID             string    `json:"id"`
	AdminID        string    `json:"admin_id"`
	Action         string    `json:"action"`
	TargetType     string    `json:"target_type"`
	TargetID       string    `json:"target_id"`
	Notes          string    `json:"notes"`
	ResponseStatus int16     `json:"response_status"`
	ErrorCode      *string   `json:"error_code,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
}

// AdminListAuditLogs handles GET /admin/audit-logs.
// Query params: admin_id, action, target_type, after (cursor by id).
func (h *Handler) AdminListAuditLogs(w http.ResponseWriter, r *http.Request) {
	adminFilter := r.URL.Query().Get("admin_id")
	actionFilter := r.URL.Query().Get("action")
	targetTypeFilter := r.URL.Query().Get("target_type")
	after := r.URL.Query().Get("after")
	limit := 50

	rows, err := h.DB.Query(r.Context(),
		`SELECT id, admin_id, action, target_type, target_id, notes,
		        response_status, error_code, created_at
		 FROM admin_audit_logs
		 WHERE ($1 = '' OR admin_id = $1)
		   AND ($2 = '' OR action = $2)
		   AND ($3 = '' OR target_type = $3)
		   AND ($4 = '' OR created_at < (SELECT created_at FROM admin_audit_logs WHERE id = $4::UUID))
		 ORDER BY created_at DESC
		 LIMIT $5`,
		adminFilter, actionFilter, targetTypeFilter, after, limit+1,
	)
	if err != nil {
		h.Logger.Error("admin list audit logs", "error", err)
		response.InternalError(w, r, h.Cfg.IsProduction())
		return
	}
	defer rows.Close()

	var logs []auditLogRow
	for rows.Next() {
		var al auditLogRow
		if err := rows.Scan(&al.ID, &al.AdminID, &al.Action,
			&al.TargetType, &al.TargetID, &al.Notes,
			&al.ResponseStatus, &al.ErrorCode, &al.CreatedAt); err != nil {
			continue
		}
		logs = append(logs, al)
	}

	var cursor response.Cursor
	if len(logs) > limit {
		logs = logs[:limit]
		cursor.Next = logs[len(logs)-1].ID
	}
	response.JSONCursor(w, http.StatusOK, logs, cursor)
}

type adminWorldRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"owner_user_id"`
	IsPublic  bool      `json:"is_public"`
	CreatedAt time.Time `json:"created_at"`
}

// AdminListWorlds handles GET /admin/worlds.
// Query params: q (name search), is_public (true/false), after.
func (h *Handler) AdminListWorlds(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	isPublicStr := r.URL.Query().Get("is_public")
	after := r.URL.Query().Get("after")
	limit := 50

	var isPublicFilter *bool
	if isPublicStr == "true" {
		v := true
		isPublicFilter = &v
	} else if isPublicStr == "false" {
		v := false
		isPublicFilter = &v
	}

	rows, err := h.DB.Query(r.Context(),
		`SELECT id, name, owner_user_id, is_public, created_at
		 FROM worlds
		 WHERE ($1 = '' OR name ILIKE '%'||$1||'%')
		   AND ($2::BOOLEAN IS NULL OR is_public = $2)
		   AND ($3 = '' OR created_at < (SELECT created_at FROM worlds WHERE id = $3::UUID))
		 ORDER BY created_at DESC
		 LIMIT $4`,
		q, isPublicFilter, after, limit+1,
	)
	if err != nil {
		h.Logger.Error("admin list worlds", "error", err)
		response.InternalError(w, r, h.Cfg.IsProduction())
		return
	}
	defer rows.Close()

	var worlds []adminWorldRow
	for rows.Next() {
		var w adminWorldRow
		if err := rows.Scan(&w.ID, &w.Name, &w.OwnerID, &w.IsPublic, &w.CreatedAt); err != nil {
			continue
		}
		worlds = append(worlds, w)
	}

	var cursor response.Cursor
	if len(worlds) > limit {
		worlds = worlds[:limit]
		cursor.Next = worlds[len(worlds)-1].ID
	}
	response.JSONCursor(w, http.StatusOK, worlds, cursor)
}

// AdminPatchWorld handles PATCH /admin/worlds/{worldID}.
// Body: { "is_public": false } — enables/disables a world.
func (h *Handler) AdminPatchWorld(w http.ResponseWriter, r *http.Request) {
	admin := middleware.AdminUserFromContext(r.Context())
	worldID := chi.URLParam(r, "worldID")

	var body struct {
		IsPublic *bool `json:"is_public"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil || body.IsPublic == nil {
		response.Error(w, r, http.StatusBadRequest, "validation_error", "is_public required")
		return
	}

	tag, err := h.DB.Exec(r.Context(),
		`UPDATE worlds SET is_public = $1, updated_at = now() WHERE id = $2`,
		*body.IsPublic, worldID,
	)
	if err != nil || tag.RowsAffected() == 0 {
		response.Error(w, r, http.StatusNotFound, "not_found", "world not found")
		return
	}

	action := "admin_disable_world"
	if *body.IsPublic {
		action = "admin_enable_world"
	}
	middleware.SetAdminAuditEntry(r.Context(), middleware.AdminAuditEntry{
		AdminID:    admin.ID,
		Action:     action,
		TargetType: "world",
		TargetID:   worldID,
	})
	w.WriteHeader(http.StatusNoContent)
}
